### ISSUE TITLE
您好，我想请问一下网络搜索完之后如何得到需要的网络结构代码？

### ISSUE THREAD

**Issue by FelixZhang7** [peteryuX/pcdarts-tf2#5]
在网络搜索完后，得到的最高精度网络结构为genotype = Genotype(normal=[('sep_conv_5x5', 1), ('dil_conv_3x3', 0), ('dil_conv_5x5', 2), ('sep_conv_3x3', 1), ('avg_pool_3x3', 3), ('avg_pool_3x3', 1), ('sep_conv_5x5', 1), ('dil_conv_5x5', 4)], normal_concat=range(2, 6), reduce=[('sep_conv_5x5', 1), ('dil_conv_3x3', 0), ('sep_conv_5x5', 2), ('sep_conv_5x5', 1), ('dil_conv_5x5', 2), ('sep_conv_3x3', 3), ('sep_conv_5x5', 4), ('sep_conv_5x5', 3)], reduce_concat=range(2, 6))，如何将这种形式变成可读可加载的网络结构呢？

**Comment by ss1k** [comment]
> 在网络搜索完后，得到的最高精度网络结构为genotype = Genotype(normal=[('sep_conv_5x5', 1), ('dil_conv_3x3', 0), ('dil_conv_5x5', 2), ('sep_conv_3x3', 1), ('avg_pool_3x3', 3), ('avg_pool_3x3', 1), ('sep_conv_5x5', 1), ('dil_conv_5x5', 4)], normal_concat=range(2, 6), reduce=[('sep_conv_5x5', 1), ('dil_conv_3x3', 0), ('sep_conv_5x5', 2), ('sep_conv_5x5', 1), ('dil_conv_5x5', 2), ('sep_conv_3x3', 3), ('sep_conv_5x5', 4), ('sep_conv_5x5', 3)], reduce_concat=range(2, 6))，如何将这种形式变成可读可加载的网络结构呢？

你好，当时你跑代码的时候有没有遇到什么问题呢？ 我直接跑代码，然后遇到了一个BatchNormalization.call()的问题， 请问能问一下你跑代码的细节吗？
